//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buhoLector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int id { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<System.DateTime> fechaPrestamo { get; set; }
    }
}
