//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buhoLector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo_Detalle
    {
        public int id { get; set; }
        public Nullable<int> prestamo_id { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<int> libro { get; set; }
    }
}
